# Site settings
title:          Wonjun Blog
description:    "All about healthcare data."
baseurl:        ""
url:            "https://hongwonjun.github.io"
google_fonts:   "Nanum+Gothic:400,700"
# Google Analytics
google_analytics: UA-47713037-1

# Author
author:
  name:         Hong Wonjun
  url:          "https://hongwonjun.github.io"
  email:

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude:
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- tale.gemspec